remote_theme: https://github.com/JV-conseil/read-the-docs-jekyll-theme

google:
  gtag: G-PXGLPMH2BL
  site_verification: ChPjQbKFflPAwOF9uuYRLEodZBgPjW5CISg0gSsViN0

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

readme_index:
  with_frontmatter: true
